/**
 * Location Fields
 *
 * Fields related to geographic location.
 */

import type { UnifiedFieldMetadata } from '../../unified-field-metadata'

export const locationFields: Record<string, UnifiedFieldMetadata> = {
  state: {
    shortcut: 's',
    label: 'State',
    question: 'What is the state?',
    description: 'US state code',
    category: 'Location',
    fieldType: 'string',
    flows: ['intake', 'policy'],
    singleInstance: true,
    options: [
      'AL',
      'AK',
      'AZ',
      'AR',
      'CA',
      'CO',
      'CT',
      'DE',
      'FL',
      'GA',
      'HI',
      'ID',
      'IL',
      'IN',
      'IA',
      'KS',
      'KY',
      'LA',
      'ME',
      'MD',
      'MA',
      'MI',
      'MN',
      'MS',
      'MO',
      'MT',
      'NE',
      'NV',
      'NH',
      'NJ',
      'NM',
      'NY',
      'NC',
      'ND',
      'OH',
      'OK',
      'OR',
      'PA',
      'RI',
      'SC',
      'SD',
      'TN',
      'TX',
      'UT',
      'VT',
      'VA',
      'WA',
      'WV',
      'WI',
      'WY',
      'DC',
    ],
  },

  zip: {
    shortcut: 'z',
    label: 'Zip Code',
    question: 'What is the zip code?',
    description: 'Zip code',
    category: 'Location',
    fieldType: 'string',
    flows: ['intake', 'policy'],
    singleInstance: true,
  },

  address: {
    shortcut: '',
    label: 'Address',
    question: 'What is the address?',
    description: 'Street address',
    category: 'Location',
    fieldType: 'string',
    flows: ['intake', 'policy'],
    singleInstance: true,
  },
}
