import type { UnifiedFieldMetadata } from '../unified-field-metadata'

/**
 * Policy-Only Field Metadata
 *
 * Fields specific to the policy analysis flow (PolicySummary).
 */

export const policyFields: Record<string, UnifiedFieldMetadata> = {
  carrier: {
    shortcut: 'c',
    label: 'Carrier',
    question: 'What is the carrier?',
    description: 'Insurance carrier name',
    category: 'Policy Information',
    fieldType: 'string',
    flows: ['policy'],
  },

  coverageLimits: {
    shortcut: '',
    label: 'Coverage Limits',
    question: '',
    category: 'Coverage',
    fieldType: 'object',
    flows: ['policy'],
    nestedFields: {
      liability: {
        shortcut: '',
        label: 'Liability',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      propertyDamage: {
        shortcut: '',
        label: 'Property Damage',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      comprehensive: {
        shortcut: '',
        label: 'Comprehensive',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      collision: {
        shortcut: '',
        label: 'Collision',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      uninsuredMotorist: {
        shortcut: '',
        label: 'Uninsured Motorist',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      personalInjuryProtection: {
        shortcut: '',
        label: 'Personal Injury Protection',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      dwelling: {
        shortcut: '',
        label: 'Dwelling',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      personalProperty: {
        shortcut: '',
        label: 'Personal Property',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      lossOfUse: {
        shortcut: '',
        label: 'Loss of Use',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      medicalPayments: {
        shortcut: '',
        label: 'Medical Payments',
        question: '',
        category: 'Coverage',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
    },
  },

  deductibles: {
    shortcut: '',
    label: 'Deductibles',
    question: '',
    category: 'Deductibles',
    fieldType: 'object',
    flows: ['policy'],
    nestedFields: {
      auto: {
        shortcut: '',
        label: 'Auto',
        question: '',
        category: 'Deductibles',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      home: {
        shortcut: '',
        label: 'Home',
        question: '',
        category: 'Deductibles',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      comprehensive: {
        shortcut: '',
        label: 'Comprehensive',
        question: '',
        category: 'Deductibles',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
      collision: {
        shortcut: '',
        label: 'Collision',
        question: '',
        category: 'Deductibles',
        fieldType: 'numeric',
        flows: ['policy'],
        min: 0,
      },
    },
  },

  effectiveDates: {
    shortcut: '',
    label: 'Effective Dates',
    question: '',
    category: 'Dates',
    fieldType: 'object',
    flows: ['policy'],
    nestedFields: {
      effectiveDate: {
        shortcut: '',
        label: 'Effective Date',
        question: '',
        category: 'Dates',
        fieldType: 'date',
        flows: ['policy'],
      },
      expirationDate: {
        shortcut: '',
        label: 'Expiration Date',
        question: '',
        category: 'Dates',
        fieldType: 'date',
        flows: ['policy'],
      },
    },
  },
}
